# Generated by Django 5.1.3 on 2025-08-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=100)),
                ('es_prestado', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(max_length=100)),
                ('libros_prestados', models.ManyToManyField(to='libr.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.estudiante')),
                ('libros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.libro')),
            ],
        ),
    ]
