# Generated by Django 5.1.3 on 2025-08-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
