# Generated by Django 5.1.3 on 2025-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0002_libro_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo_img',
            field=models.ImageField(blank=True, null=True, upload_to='codigos'),
        ),
        migrations.AddField(
            model_name='libro',
            name='estante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='estantería',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=100)),
                ('codigo_img', models.ImageField(blank=True, null=True, upload_to='codigos/')),
                ('libros_prestados', models.ManyToManyField(to='libr.libro')),
            ],
        ),
    ]
