# Generated by Django 5.1.3 on 2025-09-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0003_estudiante_codigo_img_libro_estante_libro_estantería_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='estantería',
            new_name='estanteria',
        ),
    ]
