# Generated by Django 5.1.3 on 2025-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0004_rename_estantería_libro_estanteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichas/'),
        ),
        migrations.AddField(
            model_name='maestro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichas/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_img',
            field=models.ImageField(blank=True, null=True, upload_to='codigos/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(choices=[('kinder', 'Kinder'), ('preparatoria', 'Preparatoria'), ('primero primaria', 'Primero Primaria'), ('segundo primaria', 'Segundo Primaria'), ('tercero primaria', 'Tercero Primaria'), ('cuarto primaria', 'Cuarto Primaria'), ('quinto primaria', 'Quinto Primaria'), ('sexto primaria', 'Sexto Primaria'), ('primero básico', 'Primero Básico'), ('segundo básico', 'Segundo Básico'), ('tercero básico', 'Tercero Básico'), ('cuarto bachillerato en ciencias y letras', 'Cuarto Bachillerato en Ciencias y Letras'), ('cuarto bachillerato en computación', 'Cuarto Bachillerato en Computación'), ('quinto bachillerato en ciencias y letras', 'Quinto Bachillerato en Ciencias y Letras'), ('quinto bachillerato en computación', 'Quinto Bachillerato en Computación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1),
        ),
    ]
