# Generated by Django 5.1.3 on 2025-09-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0005_estudiante_pdf_maestro_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='estudiante',
            new_name='usuario',
        ),
    ]
