# Generated by Django 5.1.3 on 2025-09-17 22:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0006_rename_estudiante_prestamo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='libros_prestados',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='es_prestado',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='libros_prestados',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 17, 22, 12, 11, 178727, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Prestamo_Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('devuelto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.libro')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.maestro')),
            ],
        ),
    ]
