# Generated by Django 5.1.3 on 2025-09-17 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0007_remove_estudiante_libros_prestados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='libros',
            new_name='libro',
        ),
        migrations.AddField(
            model_name='prestamo_maestro',
            name='fecha_prestamo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
