# Generated by Django 5.1.3 on 2025-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_barras',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='codigo_barras',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
